import Footer from "@/components/layout/footer";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/layout/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="mr-10 ml-10">
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
